receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true


  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheusremotewrite

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, spanmetrics]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite]
